// GENERATED FILE. DO NOT EDIT. Source of truth: adjacent .ts module.
export const MESSAGE_NAMES = Object.freeze({
    PING: "runtime.ping",
    OPEN_SIDEPANEL: "ui.open_sidepanel",
    AUTH_START: "auth.start",
    AUTH_STATUS_GET: "auth.status_get",
    AUTH_LOGOUT: "auth.logout",
    BOOTSTRAP_FETCH: "bootstrap.fetch",
    SIDEPANEL_LIST_RECENT_CITATIONS: "sidepanel.list_recent_citations",
    SIDEPANEL_LIST_RECENT_NOTES: "sidepanel.list_recent_notes",
    SIDEPANEL_OPEN_EDITOR: "sidepanel.open_editor",
    SIDEPANEL_OPEN_DASHBOARD: "sidepanel.open_dashboard",
    CAPTURE_CREATE_CITATION: "capture.create_citation",
    CAPTURE_CREATE_QUOTE: "capture.create_quote",
    CAPTURE_CREATE_NOTE: "capture.create_note",
    CITATION_PREVIEW: "citation.preview",
    CITATION_RENDER: "citation.render",
    CITATION_SAVE: "citation.save",
    WORK_IN_EDITOR_REQUEST: "editor.work_in_editor_request",
});
